// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FileDiff
{
    static class Vsix
    {
        public const string Id = "8f02892f-4dfd-46cc-9be3-5f670b22061a";
        public const string Name = "File Difference";
        public const string Description = @"compare files as source control comapre tool ";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "Mohamed Ebrahim Atia";
        public const string Tags = "compare , Diff , Files";
    }
}
